logsBucket: 'gs://craffy-build-logs'

options:
  machineType: E2_MEDIUM # 1 vCPU
  # logging: CLOUD_LOGGING_ONLY
  logging: GCS_ONLY

timeout: "1800s" # 20 minutes

steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'GIT_TAG=$TAG_NAME'
  - '-t'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/public/hugo:$TAG_NAME'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push to Container registry
  args:
  - 'push'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/public/hugo:$TAG_NAME'

